In [53]:
import pandas as pd 
import numpy as np
import os 

os.getcwd()
#file_out = 'choix_21_octobre_clean.csv'
#file_in = 
df = pd.read_csv('../split_columns/Resultats_choix_21_octobre_split.csv', sep = ',', index_col=False, encoding='latin-1')
print(df.columns)
print(df.head(10))
print(df.shape)

Index(['Unnamed: 0', 'Horodateur', 'Numéro de formulaire', 'ENTREE_1',
       'ENTREE_2', 'ENTREE_3', 'PLAT_1', 'PLAT_2', 'PLAT_3', 'DESSERT_1',
       'DESSERT_2', 'DESSERT_3'],
      dtype='object')
   Unnamed: 0  Horodateur Numéro de formulaire               ENTREE_1  \
0           0    12:30:58                 9V8W              choublanc
1           1    12:33:56                 8B5X             pasdentrée
2           2    12:34:46                 6X9F        rillettepoisson
3           3    12:35:27                 7B7K           minisandwich
4           4    12:35:56                 3Q7Q           minisandwich
5           5    12:36:59                 1C8S              betterave
6           6    12:37:48                 OL7Y             pasdentrée
7           7    12:39:19                 9E7A           minisandwich
8           8    12:40:23                 4B5E  saladedepommesdeterre
9           9    12:40:41                 607K              betterave

   ENTREE_2  ENTREE_3               PLAT_1      PLAT_2               PLAT_3  \
0       NaN       NaN  rotidelégumesautofu  spaghettis                  NaN
1       NaN       NaN  rotidelégumesautofu  spaghettis                  NaN
2       NaN       NaN          poissonpané  spaghettis  mousselinedepotiron
3       NaN       NaN        filetdepoulet  spaghettis  mousselinedepotiron
4       NaN       NaN          poissonpané  spaghettis  mousselinedepotiron
5       NaN       NaN          poissonpané  spaghettis  mousselinedepotiron
6       NaN       NaN          poissonpané  spaghettis                  NaN
7       NaN       NaN          poissonpané  spaghettis  mousselinedepotiron
8       NaN       NaN          poissonpané  spaghettis  mousselinedepotiron
9       NaN       NaN        filetdepoulet  spaghettis  mousselinedepotiron

         DESSERT_1        DESSERT_2 DESSERT_3
0     pasdedessert              NaN       NaN
1        roquefort  pruneauxensirop       NaN
2     crèmepraliné           orange       NaN
3  yaourtnaturebio     crèmepraliné       NaN
4           banane              NaN       NaN
5  pruneauxensirop            pomme       NaN
6        roquefort           banane     pomme
7  yaourtnaturebio           banane       NaN
8          compote              NaN       NaN
9  yaourtnaturebio  pruneauxensirop       NaN
(67, 12)

In [55]:
# les lignes prennent les valeur des numeros de formulaire au lieu d'avoir des numeros (sorte de clé etrangère)

df_meal = df.drop('Unnamed: 0', axis = 1)
df_meal = df_meal.drop('Numéro de formulaire ', axis = 1)
df_meal = df_meal.drop('Horodateur',axis=1)

print(df_meal.columns)
# on va crer la liste de tous les aliments possibles qui sera nos en-têtes de colonnes 
aliments = []
for colonne in df_meal.columns:
    for item in df_meal[colonne].unique():
        if item not in aliments and str(item) != 'nan':
            aliments.append(item)
aliments.remove('pasdentrée')
aliments.remove('pasdedessert')
#aliments.remove(nan)
print(aliments)

for aliment in aliments:
    #print(np.isnan(aliment))
    if type(aliment) != str:
        #if aliment
        aliments.remove(aliment) # pour enlever les objets de type None 
    if type(aliment) == float:
        print('cc')
        print(aliment)
        aliments.remove(aliment)

print(type(aliments[10]))

Index(['ENTREE_1', 'ENTREE_2', 'ENTREE_3', 'PLAT_1', 'PLAT_2', 'PLAT_3',
       'DESSERT_1', 'DESSERT_2', 'DESSERT_3'],
      dtype='object')
['choublanc', 'rillettepoisson', 'minisandwich', 'betterave', 'saladedepommesdeterre', 'champignons', 'saladederiz', 'pâté', 'rotidelégumesautofu', 'poissonpané', 'filetdepoulet', 'entrecôte', 'kebab', 'spaghettis', 'mousselinedepotiron', 'frites', 'salade', 'légumes', 'roquefort', 'crèmepraliné', 'yaourtnaturebio', 'banane', 'pruneauxensirop', 'compote', 'cantalaop', 'orange', 'kiwi', 'pomme']
<class 'str'>

In [56]:
# on crée maintenant un nouveau df one hot dont les colonnes sont les aliments 
df_oh = pd.DataFrame(columns=aliments)

for i in range(len(df)):
    items1 = df_meal.iloc[i].to_list()
    items = []
    #print(items1)
    for item in items1:
        if str(item) != 'nan':
            items.append(item)
    try:
        items.remove('pasdentrée')
    except:
        pass
    try : 
        items.remove('pasdedessert')
    except:
        pass
    #print(items)
    #on crée une ligne de 0 pour l'individu i 
    df_oh.loc[i] = 0
    #print(df_oh)
    # on place des 1 dans les colonnes des items choisis
    for item in items:
        #print(item)
        df_oh.iloc[i, df_oh.columns.get_loc(item)] = 1

print(df_oh)

    choublanc  rillettepoisson  minisandwich  betterave  \
0           1                0             0          0
1           0                0             0          0
2           0                1             0          0
3           0                0             1          0
4           0                0             1          0
..        ...              ...           ...        ...
62          0                1             0          0
63          0                0             0          0
64          0                0             0          0
65          0                0             0          0
66          0                0             0          0

    saladedepommesdeterre  champignons  saladederiz  pâté  \
0                       0            0            0     0
1                       0            0            0     0
2                       0            0            0     0
3                       0            0            0     0
4                       0            0            0     0
..                    ...          ...          ...   ...
62                      0            0            0     0
63                      0            1            0     0
64                      0            0            0     0
65                      0            0            0     0
66                      0            0            0     0

    rotidelégumesautofu  poissonpané  ...  roquefort  crèmepraliné  \
0                     1            0  ...          0             0
1                     1            0  ...          1             0
2                     0            1  ...          0             1
3                     0            0  ...          0             1
4                     0            1  ...          0             0
..                  ...          ...  ...        ...           ...
62                    0            1  ...          0             0
63                    0            0  ...          1             0
64                    0            1  ...          0             0
65                    0            0  ...          0             0
66                    0            0  ...          0             0

    yaourtnaturebio  banane  pruneauxensirop  compote  cantalaop  orange  \
0                 0       0                0        0          0       0
1                 0       0                1        0          0       0
2                 0       0                0        0          0       1
3                 1       0                0        0          0       0
4                 0       1                0        0          0       0
..              ...     ...              ...      ...        ...     ...
62                1       0                0        1          0       0
63                0       0                0        0          0       0
64                0       0                0        0          0       0
65                1       0                0        0          0       0
66                1       0                0        0          0       0

    kiwi  pomme
0      0      0
1      0      0
2      0      0
3      0      0
4      0      0
..   ...    ...
62     0      0
63     0      0
64     0      1
65     0      0
66     0      0

[67 rows x 28 columns]

In [58]:
df_oh.insert(0, 'Numéro de formulaire ', df['Numéro de formulaire '])
df_oh.to_csv('Resultats_choix_21_octobre_onehot.csv', sep = ';')