In [370]:
import os
import pandas as pd
import numpy as np
import math

In [371]:
os.getcwd()

"C:\\Users\\Ju'\\Documents\\INGE 3A\\IODAA_Fil_Rouge"

In [372]:
#df = pd.read_csv("merged_Forms_Choix_regroupement.csv", encoding="cp1252", on_bad_lines="skip", sep=";")
df=pd.read_csv("Merged_Octobre-Juin.csv", encoding="latin1", sep=";")

In [373]:
df

,Numéro de formulaire,Genre,Age,Taille,Poids,IMC,Activité physique,Régime particulier,Végé,Fréquence CROUS,...,cantalaop,fruit,donut,crèmedessert,tartefrboisesananas,moussechocolat,chaource,tartechocolat,fromage,pecheausirop
0,0A2A,1.0,20.0,1.755,51.0,16.558307,3.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0A4U,1.0,19.0,1.780,59.0,18.621386,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0A8B,0.0,21.0,1.650,50.0,18.365473,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0B2M,1.0,18.0,1.780,65.0,20.515086,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0C8K,1.0,18.0,1.870,83.0,23.735308,3.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E03,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496,E07,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
497,E02,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
498,E04,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
499,E01,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [374]:
L = list(df.columns)
len(L)

141

In [375]:
df["count_fruits"] = df["orange"] + df["pomme"] + df["kiwi"] + df["compote"] + df["poire"] + df["pruneauxausirop"] + df["banane"] + df["cocktailfruitsexotiques"] + df["fruit"] + df["pecheausirop"]

In [376]:
sup = ["orange","pomme","kiwi", "compote","poire","pruneauxausirop","banane","cocktailfruitsexotiques","fruit", "pecheausirop"]
for s in sup:
       L.remove(s)
len(L)

131

In [377]:
df["count_fromage"] = df["emmental"] + df["bleudauvergneaop"] + df["roquefort"] + df["cantalaop"] + df["fromage"] + df["mimolette"] + df["chaource"]

In [378]:
sup = ["emmental","bleudauvergneaop","roquefort", "cantalaop","fromage","mimolette", "chaource"]
for s in sup:
       L.remove(s)
len(L)

124

In [379]:
df["count_saladefeculents"] = df["saladepates"] + df["saladepommesdeterre"] + df["saladeriz"]

In [380]:
sup = ["saladepates","saladepommesdeterre","saladeriz"]
for s in sup:
       L.remove(s)
len(L)

121

In [381]:
df["count_crudites"] = df["chou"] + df["saladelentilles"] + df["champignons"] + df["carottesrapees"] + df["artichauts"] + df["coeursdepalmiers"] + df["tomates"] + df["betterave"] + df["saladesoja"] + df["endives"] + df["betteravespommesechalotes"] + df["saladeverte"]

In [382]:
sup = ["chou","saladelentilles","champignons","carottesrapees","artichauts","coeursdepalmiers","tomates","betterave","saladesoja", "endives", "betteravespommesechalotes","saladeverte"]
for s in sup:
       L.remove(s)
len(L)

109

In [383]:
df["count_charcuterie"] = df["oeufmimosa"] + df["salami"] + df["surimi"] + df["minisandwich"] + df["pâté"] + df["rillettepoisson"] + df["saucisson"] + df["sardines"] + df["pizzaentree"]

In [384]:
sup = ["oeufmimosa","salami","surimi","minisandwich","pâté","rillettepoisson","saucisson","sardines", "pizzaentree"]
for s in sup:
    L.remove(s)
len(L)

100

In [385]:
df["count_viande"] = df["boeufbourguignon"] + df["kebab"] + df["faux-filet"] + df["pizzamerguezpoivrons"] + df["hamburger"] + df["escalopeviennoise"] + df["filetdepoulet"] + df["pizza"] + df["cordonbleu"] + df["boulettesviande"] + df["pizzakebab"] + df["entrecote"] + df["chipo"] + df["burger"] + df["escalopedeporc"] + df["grillades"]

In [386]:
sup = ["boeufbourguignon","kebab","faux-filet","pizzamerguezpoivrons","hamburger","escalopeviennoise","filetdepoulet","pizza","cordonbleu","boulettesviande","pizzakebab","entrecote", "chipo", "burger", "escalopedeporc", "grillades"]
for s in sup:
    L.remove(s)
len(L)

84

In [387]:
df["count_poisson"] = df["feuilletesaumonoseille"] + df["pavedecabillaud"] + df["pavedepoissonbordelaise"] + df["poissonpane"] + df["tartesaumon"]

In [388]:
sup = ["feuilletesaumonoseille","pavedecabillaud","pavedepoissonbordelaise","poissonpane","tartesaumon"]
for s in sup:
    L.remove(s)
len(L)

79

In [389]:
df["count_vege"] = df["risottocourgettes"] + df["pizzaraclette"] + df["tajinevege"] + df["burgervege"] + df["rotilegumestofu"] + df["lasagnesvg"] + df["gnocchispestovege"]

In [390]:
sup = ["risottocourgettes","pizzaraclette","tajinevege","burgervege", "rotilegumestofu", "lasagnesvg", "gnocchispestovege"]
for s in sup:
    L.remove(s)
len(L)

72

In [391]:
df["count_yaourt"] = df["yaourtauxfruits"] + df["faissellenature"] + df["yaourtnature"] + df["fromageblancfruitsrouges"] + df["petitsuissenature"] + df["fromageblanc"]

In [392]:
sup = ["yaourtauxfruits","faissellenature","yaourtnature","fromageblancfruitsrouges", "petitsuissenature", "fromageblanc"]
for s in sup:
    L.remove(s)
len(L)

66

In [393]:
df["count_dessertgourmand"] = df["oeufalaneige"] + df["madeleine"] + df["tarteauxfruits"] + df["parisbrest"] + df["gateaudesemoule"] + df["donut"] + df["tartefrboisesananas"] + df["tartechocolat"]

In [394]:
sup = ["oeufalaneige","madeleine","tarteauxfruits","parisbrest", "gateaudesemoule", "donut", "tartefrboisesananas", "tartechocolat"]
for s in sup:
    L.remove(s)
len(L)

58

In [395]:
df["count_cremedessert"] = df["moussenoixdecoco"] + df["liegeois"] + df["cremepraline"] + df["flancchocolat"] + df["crèmedessert"] + df["moussechocolat"]

In [396]:
sup = ["moussenoixdecoco","liegeois","cremepraline","flancchocolat", "crèmedessert","moussechocolat"]
for s in sup:
    L.remove(s)
len(L)

52

In [397]:
df["count_accompagnement"] = df["torsades"] + df["brocolis"] + df["frites"] + df["ratatouille"] + df["pommesdeterrevapeur"] + df["juliennedelegumes"] + df["riz"] + df["spaghettis"] + df["mousselinedepotiron"] + df["legumes"] + df["semoule"] + df["poeleemeridionale"]

In [398]:
sup = ["torsades","brocolis","frites","ratatouille","pommesdeterrevapeur","juliennedelegumes","riz","spaghettis", "mousselinedepotiron", "legumes", "semoule", "poeleemeridionale"]
for s in sup:
    L.remove(s)
len(L)

40

In [399]:
L

['Numéro de formulaire',
 'Genre',
 'Age',
 'Taille',
 'Poids',
 'IMC',
 'Activité physique',
 'Régime particulier',
 'Végé',
 'Fréquence CROUS',
 'Equilibre alim',
 'Seule ou en groupe',
 'Nb groupe entrée',
 'Proximité',
 'Connaissance',
 'Parti groupe',
 'Influ sociale',
 'Percept senso',
 'Nb file',
 'Faim',
 'Stress',
 'Nb convives',
 'Ami 1',
 'Ami 2',
 'Ami 3',
 'Ami 4',
 'Ami 5',
 'Ami 6',
 'Ami 7',
 'Ami 8',
 'Ami 9',
 'Ami 10',
 'Ami 11',
 'Ami 12',
 'Ami 13',
 'Ami 14',
 'Ami 15',
 'Ami 16',
 'Ami 17',
 'Horodateur']

In [400]:
#print(df.columns.get_loc("onehot_fruits"))
print(df.columns.get_loc("count_fruits"))
#print(df.columns[118])

141

In [401]:
model_col=pd.read_csv("u-merged_Forms_Choix_regrmt_Hélène.csv", encoding="latin1", sep=";")

In [402]:
model_col.iloc[0,:]

<<<<<<< Updated upstream    onehot_accompagnement
Name: (nan, index, Genre, Age, Taille, Poids, IMC, Activité physique, Régime particulier, Végé, Fréquence CROUS, Equilibre alim, Seule ou en groupe, Nb groupe entrée, Proximité, Connaissance, Parti groupe, Influ sociale, Percept senso, Nb file, Faim, Stress, Nb convives, Ami 1, Ami 2, Ami 3, Ami 4, Ami 5, Ami 6, Ami 7, Ami 8, Ami 9, Ami 10, Ami 11, Ami 12, Ami 13, Ami 14, Ami 15, Ami 16, Ami 17, onehot_fruits, onehot_fromage, onehot_crudites, onehot_saladefeculents, onehot_charcuterie, onehot_viande, onehot_poisson, onehot_vege, onehot_yaourt, onehot_dessertgourmand, onehot_cremedessert), dtype: object

In [403]:
for col in df.columns[df.columns.get_loc("count_fruits"):]:
    df['onehot_' + col[6:]] = np.where(df[col] > 0,1,0)
df

,Numéro de formulaire,Genre,Age,Taille,Poids,IMC,Activité physique,Régime particulier,Végé,Fréquence CROUS,...,onehot_saladefeculents,onehot_crudites,onehot_charcuterie,onehot_viande,onehot_poisson,onehot_vege,onehot_yaourt,onehot_dessertgourmand,onehot_cremedessert,onehot_accompagnement
0,0A2A,1.0,20.0,1.755,51.0,16.558307,3.0,1.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
1,0A4U,1.0,19.0,1.780,59.0,18.621386,0.0,0.0,0.0,2.0,...,0,1,0,1,0,0,1,0,0,1
2,0A8B,0.0,21.0,1.650,50.0,18.365473,0.0,0.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
3,0B2M,1.0,18.0,1.780,65.0,20.515086,1.0,0.0,0.0,2.0,...,0,0,1,1,0,0,1,0,0,1
4,0C8K,1.0,18.0,1.870,83.0,23.735308,3.0,0.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E03,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,1,0,0,0,0,1,1,0,0,0
496,E07,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,0,0,1
497,E02,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,...,0,0,0,0,0,1,0,0,0,0
498,E04,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,1,0,1
499,E01,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,0,0,1

In [404]:
def round_to_nearest_IMC_float(x) : 
    if math.isnan(x):
        return x
    
    modulo = round(x)%5
    #print(x, modulo)
    if modulo > 2.5 :
        to_return = round(x) + (5-modulo)
        return to_return
    
    elif modulo == 0 : 
        return round(x)
    
    else : 
        to_return = round(x) - modulo
        return to_return
    
df["IMC"] = df["IMC"].map(lambda IMC : round_to_nearest_IMC_float(IMC))
print(df["IMC"])

0      15.0
1      20.0
2      20.0
3      20.0
4      25.0
       ...
495     NaN
496     NaN
497     NaN
498     NaN
499     NaN
Name: IMC, Length: 500, dtype: float64

In [405]:
#Réduction en classes des colonnes avec des valeurs très diverses pour allégre le one-hot encoding
def round_to_nearest_IMC(x) : 
    modulo = int(x.split(",")[0])%5
    print("Data : ", int(x.split(",")[0]), modulo)
    if modulo > 2.5 :
        to_return = int(x.split(",")[0]) + (5-modulo)
        print("Return : ", to_return)
        return to_return
    
    elif modulo == 0 : 
        print("Return : ", int(x.split(",")[0]))
        return int(x.split(",")[0])
    
    else : 
        to_return = int(x.split(",")[0]) - modulo
        print("Return : ", to_return)
        return to_return
    
#df["IMC"] = df["IMC"].map(lambda IMC : round_to_nearest_IMC(IMC))
#print(df["IMC"])

In [406]:
df.to_csv("Octbre_Juin_Choix_Forms_Regroup_allCol.csv", sep=';', encoding="latin1", index=False)

In [407]:
col_onehot = list(range(df.columns.get_loc("Ami 17")+1)) + list(range(df.columns.get_loc("onehot_fruits"),df.shape[1]))
smaller = df.iloc[:,col_onehot]
smaller

,Numéro de formulaire,Genre,Age,Taille,Poids,IMC,Activité physique,Régime particulier,Végé,Fréquence CROUS,...,onehot_saladefeculents,onehot_crudites,onehot_charcuterie,onehot_viande,onehot_poisson,onehot_vege,onehot_yaourt,onehot_dessertgourmand,onehot_cremedessert,onehot_accompagnement
0,0A2A,1.0,20.0,1.755,51.0,15.0,3.0,1.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
1,0A4U,1.0,19.0,1.780,59.0,20.0,0.0,0.0,0.0,2.0,...,0,1,0,1,0,0,1,0,0,1
2,0A8B,0.0,21.0,1.650,50.0,20.0,0.0,0.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
3,0B2M,1.0,18.0,1.780,65.0,20.0,1.0,0.0,0.0,2.0,...,0,0,1,1,0,0,1,0,0,1
4,0C8K,1.0,18.0,1.870,83.0,25.0,3.0,0.0,0.0,2.0,...,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E03,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,1,0,0,0,0,1,1,0,0,0
496,E07,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,0,0,1
497,E02,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,...,0,0,0,0,0,1,0,0,0,0
498,E04,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,1,0,1
499,E01,1.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,...,0,0,0,1,0,0,0,0,0,1

In [408]:
smaller.to_csv("Octbre_Juin_Choix_Forms_Regroup_onehot.csv", sep=';', encoding="latin1", index=False)