## Chargement packages et données

In [1]:
import numpy as np
import pandas as pd
import os
import math
import re 
os.getcwd()

'/Users/helenephilippe/Desktop/Projet_MIChoCo/data_CROUS/data_processed/merged_one_hot'

## Sauvegarde d'un fichier concatenant formulaire et choix pour chaque sujet

In [2]:
#concatenation du formulaire avec les choix 
choix = pd.read_csv("Merged_Choix.csv", encoding='latin1', sep=",") 
formulaire = pd.read_csv("Merged_Formulaires.csv", encoding='latin1')

In [3]:
formulaire

,N° Formulaire,Genre,Age,Taille,Poids,IMC,Activité physique,Régime particulier,Végé,Fréquence CROUS,...,Ami 8,Ami 9,Ami 10,Ami 11,Ami 12,Ami 13,Ami 14,Ami 15,Ami 16,Ami 17
0,2E8L,1,20,1.84,72.0,21.266541,3,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6Z9V,1,19,1.75,79.0,25.795918,1,1,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1P5N,1,19,1.74,74.0,24.441802,2,1,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1L0F,1,21,1.70,51.0,17.647059,2,1,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6U1H,1,18,1.78,71.0,22.408787,2,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,2Z9A,1,19,1.82,70.0,21.132713,3,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,6S8Q,0,21,1.75,60.0,19.591837,2,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,7B7K,0,25,1.54,75.0,31.624220,1,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,6X9F,1,28,1.75,75.0,24.489796,1,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,9B8H,1,20,1.80,80.0,24.691358,2,0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
choix

,Numéro de formulaire,Horodateur,chou,saladelentilles,champignons,carottesrapees,oeufmimosa,saladepates,artichauts,salami,...,poire,pruneauxausirop,emmental,bleudauvergneaop,cremepraline,gateaudesemoule,cocktailfruitsexotiques,legumes,roquefort,cantalaop
0,6P4Y,12:30:48,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2H8Z,12:32:01,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,8M4T,12:32:45,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3G0E,12:32:51,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8K6E,12:33:28,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2D7O,13:05:03,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433,8J2L,13:05:14,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
434,1L4G,13:05:35,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
435,1M2Q,13:05:41,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
436,254Q,13:05:42,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [5]:
pos_tofu = choix.columns.get_loc('rotilegumestofu')  #39
choix['temp_tofu'] = choix['rotidelegumestofu'] + choix['rotilegumestofu']
choix.pop('rotilegumestofu')
choix.pop('rotidelegumestofu')
choix.insert(39, 'rotilegumestofu', choix.pop('temp_tofu'))

In [6]:
choix

,Numéro de formulaire,Horodateur,chou,saladelentilles,champignons,carottesrapees,oeufmimosa,saladepates,artichauts,salami,...,poire,pruneauxausirop,emmental,bleudauvergneaop,cremepraline,gateaudesemoule,cocktailfruitsexotiques,legumes,roquefort,cantalaop
0,6P4Y,12:30:48,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2H8Z,12:32:01,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,8M4T,12:32:45,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3G0E,12:32:51,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8K6E,12:33:28,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2D7O,13:05:03,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433,8J2L,13:05:14,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
434,1L4G,13:05:35,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
435,1M2Q,13:05:41,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
436,254Q,13:05:42,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

#### Merging

In [7]:
#on associe choix et formulaire par le numero de formulaire
choix = choix.set_index("Numéro de formulaire ")
formulaire = formulaire.set_index("N° Formulaire")
#on merge les deux dataframes
final = pd.merge(formulaire, choix, left_index=True, right_index=True)

#### Suppression des lignes en double

In [8]:
final.shape

(332, 120)

In [9]:
final.reset_index(inplace = True)

In [10]:
final.drop_duplicates(subset = 'index', keep = 'first', inplace=True)

In [11]:
final.shape

(326, 121)

#### Résultats

In [12]:
final.set_index("index")

,Genre,Age,Taille,Poids,IMC,Activité physique,Régime particulier,Végé,Fréquence CROUS,Equilibre alim,...,poire,pruneauxausirop,emmental,bleudauvergneaop,cremepraline,gateaudesemoule,cocktailfruitsexotiques,legumes,roquefort,cantalaop
index,,,,,,,,,,,,,,,,,,,,,
0A2A,1,20,1.755,51.0,16.558307,3,1,0,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0A4U,1,19,1.780,59.0,18.621386,0,0,0,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0A8B,0,21,1.650,50.0,18.365473,0,0,0,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0B2M,1,18,1.780,65.0,20.515086,1,0,0,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0C8K,1,18,1.870,83.0,23.735308,3,0,0,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9V8W,0,21,1.700,57.0,19.723183,1,1,1,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9W3C,1,18,1.750,55.0,17.959184,3,0,0,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9W3F,1,32,1.820,79.0,23.849777,1,0,0,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9X1Z,0,22,1.680,56.0,19.841270,2,0,0,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9Z3C,1,21,1.750,61.0,19.918367,2,1,1,2,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
final.to_csv("merged_Forms_Choix.csv", encoding='latin1')